[versions]
java = "21"
fabric-loader = "0.16.7"
paper-api = "1.21.1-R0.1-SNAPSHOT"

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
